#!/bin/sh -e

cd src/

make DESTDIR="$1" buildworld
make DESTDIR="$1" buildkernel
make DESTDIR="$1" installworld
make DESTDIR="$1" installkernel

# Remove 'blacklisted' cacerts, since this is managed by us.
rm -rf "${1:?}/etc/ssl/blacklisted"
rm -rf "${1:?}/usr/share/certs/blacklisted"

# Remove some broken files.
# TODO: Move this to the hook, and try to have this be automatic.
# Randomly broken symlinks?
rm -rf "${1:?}/usr/lib/./include"
rm -rf "${1:?}/usr/share/nls/./POSIX"
rm -rf "${1:?}/usr/share/nls/./en_US.US_ASCII"
# More headache than it's worth.
rm -rf "${1:?}/usr/tests"
rm -rf "${1:?}/usr/lib/debug"
# This file is symlink to a file under /usr/tests, so remove it.
rm -rf "${1:?}/usr/lib/libxo/encoder/test.enc"
