#!/bin/sh -e

cd src/

# Create temporary links so that every file
# is created into the same namespace.
mkdir -p \
    "$1/usr/bin" \
    "$1/usr/lib" \
    "$1/usr/libexec"

ln -sf usr/bin     "$1/bin"
ln -sf bin         "$1/usr/sbin"
ln -sf bin         "$1/sbin"
ln -sf usr/lib     "$1/lib"
ln -sf usr/libexec "$1/libexec"


make DESTDIR="$1" buildworld
make DESTDIR="$1" buildkernel
make DESTDIR="$1" installworld
make DESTDIR="$1" installkernel

# Now that we have all the programs/libraries in
# our preferred location, we can unlink all those
# directories.
for link in bin usr/sbin sbin lib libexec ; do
    unlink "$1/$link"
done
