#!/bin/sh -e

# Make the build system run /bin/true to generate
# a dummy file so our pre-generated one is used.
sed 's/fcobjshash\.h/fcjunk.h/' src/Makefile.in > _
mv -f _ src/Makefile.in

./configure \
    GPERF=true \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-docs \
    --disable-nls

gmake
gmake install
